# Generated by Django 6.1.1 on 2026-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('Name', models.CharField(max_length=15)),
                ('Alt_num', models.IntegerField()),
                ('Reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Father_name', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField()),
                ('Vehicle_Type', models.TextField()),
            ],
        ),
    ]
