# Generated by Django 6.1.1 on 2026-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Reg_no',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
